### ISSUE TITLE
Android Sample provider

### ISSUE THREAD

**Issue by gregtse2** [Purebred/SampleKeyProvider#2]
Hi - we'd like to get this running on Android, is there a sample or any guidance for it? 
Thanks!

**Comment by carl-wallace** [comment]
SampleKeyProvider is for iOS and is intended to facilitate testing the KeyShareConsumer app. The KeyShareConsumer app contains code similar to what one would use to integrate support for importing keys from the Purebred app. For Android, the AliasShareProvider is a similar app and is intended to facilitate testing the AliasShareConsumer app. The AliasShareConsumer app contains code similar to what one would use to integrate support for imports aliases and certificates from the Purebred app. There is no analog to KeyShareConsumer/SampleKeyProvider for Android as there is no need to share keys. Keys are already accessible via the KeyChain API.

**Comment by gregtse2** [comment]
Terrific! Thanks so much Carl!
